<?php
/**
 * Plugin Name: Intent Box
 * Plugin URI: https://www.intentbox.me/
 * Description: Convert your visitors with the right calls-to-action, at the right time.
 * Author: Intent Box Team
 * Author URI: https://getintentbox.surge.sh
 * Version: 1.0
 * Text Domain: intent-box
 *

 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 2, as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * @package Intent-Box
 * @author Intent Box Team
 * @version 1.0
 */

/**
 * Print direct link to Intent Box Page
 *
 * Fetches array of links generated by WP Plugin admin page ( Deactivate | Edit )
 * and inserts a link to the Simple Scripts admin page
 *
 * @since  1.0
 * @param  array $links Array of links generated by WP in Plugin Admin page.
 * @return array $links Array of links to be output on Plugin Admin page.
 */
function intentbox_settings_link( $links ) {
	$settings_page = '<a href="' . admin_url('tools.php?page=intent-box.php' ) .'">Integration</a>';
	array_unshift( $links, $settings_page );
	return $links;
}
$plugin = plugin_basename(__FILE__);
add_filter( "plugin_action_links_$plugin", 'intentbox_settings_link' );
/**
 * Register text domain
 *
 * @since 1.0
 */
function intentbox_textdomain() {
	load_plugin_textdomain('intentbox');
}
add_action('init', 'intentbox_textdomain');
/**
 * Delete Settings on Uninstall
 *
 * @since 1.0
 */
function intentbox_uninstall() {
	unregister_setting( 'intentbox_settings_group', 'intentbox_settings' );
}
register_uninstall_hook( __FILE__, 'intentbox_uninstall' );
/**
 * Print Header Scripts
 *
 * @since 1.0
 */
function intentbox_header_scripts() {
	ob_start();
		$options = get_option( 'intentbox_settings' );
		$sfhs_header = isset( $options['header_scripts_input'] ) ? $options['header_scripts_input'] : '';
		echo "<script type=text/javascript>\n";
		if ( isset( $options['intentbox_credit'] ) ) {
			echo "// Rendered by Intent Box
// http://wordpress.org/plugins/intent-box/
 \n";
		}
		echo $sfhs_header;
		echo "\n</script>";
	echo ob_get_clean();
}
/**
 * Print Footer Scripts
 *
 * @since 1.0
 */
function intentbox_footer_scripts() {
	ob_start();
		$options = get_option( 'intentbox_settings' );
		$sfhs_footer = isset( $options['footer_scripts_input'] ) ? $options['footer_scripts_input'] : '';
		echo "<script type=text/javascript>\n";
		if ( isset( $options['intentbox_credit'] ) ) {
			echo "// Rendered by Intent Box
// http://wordpress.org/plugins/intent-box/
\n";
		}
		echo $sfhs_footer;
		echo "\n</script>";
	echo ob_get_clean();
}
/**
 * Attaches Scripts to Hooks to be rendered
 *
 * @since 1.0
 */
function intentbox_render_scripts() {
	$options = get_option( 'intentbox_settings' );
	if ( isset( $options['header_scripts_input'] ) )
		add_action( 'wp_head', 'intentbox_header_scripts' );
	if ( isset( $options['footer_scripts_input'] ) )
		add_action( 'wp_footer', 'intentbox_footer_scripts' );
}
add_action( 'init', 'intentbox_render_scripts' );
/**
 * Register "Header/Footer Scripts" submenu in "Tools" Admin Menu
 *
 * @since 1.0
 */
function intentbox_register_submenu_page() {
	add_management_page( __( 'Intent Box', 'intentbox' ), __( 'Intent Box', 'intentbox' ), 'edit_themes', basename(__FILE__), 'intentbox_render_submenu_page' );
}
add_action( 'admin_menu', 'intentbox_register_submenu_page' );
/**
 * Register settings
 *
 * @since 1.0
 */
function intentbox_register_settings() {
	register_setting( 'intentbox_settings_group', 'intentbox_settings' );
	add_settings_section( 'intentbox_primary_section', __( '', 'rt_polls' ), 'intentbox_primary_section_cb', __FILE__ );
	add_settings_field( 'intentbox_header_scripts_input', __( 'Integration Code', 'rt_polls' ), 'intentbox_header_scripts_input', __FILE__, 'intentbox_primary_section' );
}

add_action('admin_init', 'intentbox_register_settings');
/**
 * Render Primary Section text
 *
 * @since  1.0
 */
function intentbox_primary_section_cb() {}
/**
 * Render Header Scripts Input
 *
 * @since  1.0
 */
function intentbox_header_scripts_input() {
	$options  = get_option('intentbox_settings');
	$field_value   = isset( $options['header_scripts_input'] ) ? $options['header_scripts_input'] : ''; ?>
	<textarea id="header-scripts-input" name="intentbox_settings[header_scripts_input]" placeholder="Add your Integration code here!" style="width:650px; height: 200px; boder:none;overflow:hidden;" ><?php echo esc_html( $field_value ) ?></textarea>
	<?php
}

/**
 *
 * Shortcode Intentbox
 *
 */

function intentbox_shortcode( $atts ) {
  $a = shortcode_atts( array(
      'code' => 'Your-Code-Here',
  ), $atts );
  
  if ($a['code'] === 'Your-Code-Here') {
    return;
  }

  ?>
  <script type="text/javascript">
    IntentBox.show('<?php echo $a['code'] ?> ')
  </script>
  <?php
  
}
add_shortcode( 'intentbox', 'intentbox_shortcode' );


/**
 * Render Credit Author checkbox
 *
 * @since  1.0
 */
function intentbox_credit() {
	$options = get_option('intentbox_settings');
	$field_value = isset( $options['intentbox_credit'] ) ? $options['intentbox_credit'] : 1;
	?>
    <input type="checkbox" name="intentbox_settings[intentbox_credit]" value="1" <?php checked( 1, $field_value ) ?> />
    <p style="width: 300px;" class="description">
        <?php _e( 'Print credit to the author along with your script(s).  Nothing will be publicly visible on your site.', 'intentbox' ) ?>
    </p>
	<?php
}
/**
 * Render Plugin submenu page
 *
 * @since 1.0
 */
function intentbox_render_submenu_page() {
	if ( isset( $_GET['settings-updated'] ) ) : ?>
		<div id="message" class="updated"><p><?php _e( 'Integration script added successfully.' ); ?></p></div>
	<?php endif; ?>
	<div class="wrap" style="background-color: #fff;padding: 40px;border-radius: 10px;">
		<?php screen_icon(); ?>
		<h2><?php _e( 'Intent Box', 'intentbox' ); ?></h2>
		<h4 style="font-size: 16px;font-weight: 300;margin-top: 5px;"><?php _e('Increase your leads with smart advertising. Show Intent Boxes according to the intentions of your users and increase your conversion, anywhere.', 'intentbox') ?></h4>
		<p style="margin: 30px 0;"><a style="font-weight: 600;text-decoration: none;font-weight: 600;text-decoration: none;height: 40px;background-color: #ffffff;padding: 10px;border-radius: 20px;color: #3f51b5;border: 1px solid #3f51b5;" target="_blank" href="http://intentbox.surge.sh/dashboard/create-campaign">Create new Intent Box</a></p>
		<form name="intentbox-form" action="options.php" method="post" enctype="multipart/form-data">
			<?php settings_fields('intentbox_settings_group'); ?>
			<?php do_settings_sections( __FILE__ ); ?>
			<p class="submit">
				<input style="background-color: #3F51B5;color: #fff;height: 40px;border:none;text-shadow: none;box-shadow: none;" name="scripts-submit" type="submit" class="button-primary" value="<?php esc_attr_e( 'Add Integration Script', 'intentbox' ); ?>" />
			</p>
		</form>
	</div>
	<?php
}